name: Publish Artifacts
on:
  workflow_dispatch:
jobs:
  release:
    strategy:
      matrix:
        # Use these Java versions
        java: [17]
        # and run on both Linux and Windows
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Antimatter
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Fetch tags
        run: git fetch --tags
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build --stacktrace
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          GITHUB_RELEASE: true
      - name: Generate Changelog
        run: ./mkchangelog.sh
      - name: Publish forge jar to curseforge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          # You don't need this section if you don't want to publish
          # your assets to CurseForge
          curseforge-id: 514578
          curseforge-token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          version-type: alpha
          changelog-file: changelog-generated.md
          files-primary: forge/build/libs/!(*-@(dev-shadow|sources|javadoc)).jar
          files-secondary: forge/build/libs/*-@(dev-shadow|sources|javadoc).jar
      - name: Publish fabric jar to curseforge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          # You don't need this section if you don't want to publish
          # your assets to CurseForge
          curseforge-id: 514578
          curseforge-token: ${{ secrets.CURSEFORGE_API_TOKEN }}
          version-type: alpha
          changelog-file: changelog-generated.md
          files-primary: fabric/build/libs/!(*-@(dev-shadow|sources|javadoc)).jar
          files-secondary: fabric/build/libs/*-@(dev-shadow|sources|javadoc).jar
